//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devyt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_ChiNhanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin_ChiNhanh()
        {
            this.Admin_Kho = new HashSet<Admin_Kho>();
            this.Admin_TaiKhoan = new HashSet<Admin_TaiKhoan>();
        }
    
        public int Id { get; set; }
        public string ChiNhanh { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string Hotline { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_Kho> Admin_Kho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_TaiKhoan> Admin_TaiKhoan { get; set; }
    }
}
