//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devyt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Kho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin_Kho()
        {
            this.Admin_ViTriKho = new HashSet<Admin_ViTriKho>();
        }
    
        public int Id { get; set; }
        public string TenKho { get; set; }
        public Nullable<int> ChiNhanhId { get; set; }
    
        public virtual Admin_ChiNhanh Admin_ChiNhanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_ViTriKho> Admin_ViTriKho { get; set; }
    }
}
