//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devyt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc_TaiXe
    {
        public int Id { get; set; }
        public string TenLaiXe { get; set; }
        public string SoDienThoai { get; set; }
        public string GPLX { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string ZaloId { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> ChiNhanhId { get; set; }
    }
}
