//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devyt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc_XeVanTai
    {
        public int Id { get; set; }
        public string SoXe { get; set; }
        public Nullable<System.DateTime> HanDangKiem { get; set; }
        public Nullable<bool> XeThue { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> ChiNhanhId { get; set; }
    }
}
