//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devyt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc_DiaDiem
    {
        public int Id { get; set; }
        public string TenDiaDiem { get; set; }
        public string KinhDo { get; set; }
        public string ViDo { get; set; }
    }
}
