//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devyt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc_NhaCungCap
    {
        public int Id { get; set; }
        public string TenNhaCungCap { get; set; }
        public string DiaChi { get; set; }
        public string MaSoThue { get; set; }
        public string TenVietTat { get; set; }
    }
}
