//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devyt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapXuat_HangNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhapXuat_HangNhap()
        {
            this.NhapXuat_HangXuat = new HashSet<NhapXuat_HangXuat>();
        }
    
        public int Id { get; set; }
        public string TenHang { get; set; }
        public Nullable<int> SoKien { get; set; }
        public string SoContNhap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string XuatXu { get; set; }
        public Nullable<int> LoHangId { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> ConTon { get; set; }
    
        public virtual NhapXuat_LoHang NhapXuat_LoHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhapXuat_HangXuat> NhapXuat_HangXuat { get; set; }
    }
}
