//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devyt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapXuat_HangXuat
    {
        public int Id { get; set; }
        public Nullable<int> HangNhapId { get; set; }
        public Nullable<int> SoKien { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public string SoToKhai { get; set; }
        public string SoContXuat { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> TonKhoId { get; set; }
    
        public virtual NhapXuat_HangNhap NhapXuat_HangNhap { get; set; }
    }
}
