//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devyt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanTai_ChuyenDieuVan
    {
        public int Id { get; set; }
        public Nullable<int> DonViVanTaiId { get; set; }
        public Nullable<int> LenhVanChuyenId { get; set; }
        public Nullable<int> LenhVanChuyen2Id { get; set; }
        public string SoCont { get; set; }
        public string SoCont2 { get; set; }
        public Nullable<decimal> TrongTai { get; set; }
        public Nullable<decimal> TrongTai2 { get; set; }
        public Nullable<int> XeVanTaiId { get; set; }
        public Nullable<int> TaiXeId { get; set; }
        public Nullable<System.DateTime> NgayVanTai { get; set; }
        public Nullable<System.DateTime> NgayHoanTat { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> ChiNhanhId { get; set; }
        public Nullable<bool> ChieuDi { get; set; }
        public Nullable<int> DinhMucDau { get; set; }
        public Nullable<decimal> DoanhThuCuoc { get; set; }
        public Nullable<decimal> DoanhThuKhac { get; set; }
        public Nullable<decimal> TongDoanhThu { get; set; }
        public Nullable<decimal> ChiPhiTienDuong { get; set; }
        public Nullable<decimal> ChiPhiKhac { get; set; }
        public Nullable<decimal> TongChiPhi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> DiemDiId { get; set; }
        public Nullable<int> DiemDenId { get; set; }
    }
}
