//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devyt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanTai_KeHoachVanTai
    {
        public int Id { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public string BillBook { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayHoanTat { get; set; }
        public Nullable<int> DiemDiId { get; set; }
        public Nullable<int> DiemDenId { get; set; }
        public Nullable<int> LoaiHangId { get; set; }
        public string MatHang { get; set; }
        public Nullable<int> DonViVanTaiId { get; set; }
        public string NguoiLienLac { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<int> ChiNhanhId { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
